# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: director.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tick_pb2 as tick__pb2
from . import util_pb2 as util__pb2
from . import scenario_pb2 as scenario__pb2
from . import oracle_pb2 as oracle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64irector.proto\x12\x0eworld.director\x1a\ntick.proto\x1a\nutil.proto\x1a\x0escenario.proto\x1a\x0coracle.proto\"\xb4\x01\n\x0cTurnScenario\x12\x0c\n\x04turn\x18\x01 \x01(\x08\x12\x18\n\x0bscenario_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\"\n\x15scenario_dependencies\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0escenario_state\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x0e\n\x0c_scenario_idB\x18\n\x16_scenario_dependenciesB\x11\n\x0f_scenario_state2\xf9\x01\n\x08\x44irector\x12\x45\n\rset_persistor\x12\x17.world.util.GRPCAddress\x1a\x1b.world.util.RequestResponse\x12J\n\rturn_scenario\x12\x1c.world.director.TurnScenario\x1a\x1b.world.util.RequestResponse\x12Z\n\x16list_running_scenarios\x12\x18.world.util.EmptyMessage\x1a&.world.scenario.ScenarioDependencyListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'director_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TURNSCENARIO._serialized_start=89
  _TURNSCENARIO._serialized_end=269
  _DIRECTOR._serialized_start=272
  _DIRECTOR._serialized_end=521
# @@protoc_insertion_point(module_scope)
