# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10instrument.proto\x12\x10world.instrument\x1a\nutil.proto\"}\n\x08\x45xchange\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x03(\t\x12,\n\ropening_times\x18\x03 \x03(\x0b\x32\x15.world.util.TimeRange\x12\'\n\x08holidays\x18\x04 \x03(\x0b\x32\x15.world.util.TimeRange\"\x95\x01\n\nInstrument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x03(\t\x12.\n\x04kind\x18\x03 \x01(\x0e\x32 .world.instrument.InstrumentKind\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\x0c\x12\x0e\n\x06\x61\x63tive\x18\x05 \x01(\x08\x12\x11\n\x04isin\x18\x06 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_isin\"<\n\x0eInstrumentList\x12*\n\x04list\x18\x01 \x03(\x0b\x32\x1c.world.instrument.Instrument*o\n\x0eInstrumentKind\x12\x0b\n\x07Generic\x10\x00\x12\t\n\x05Stock\x10\x01\x12\x07\n\x03\x45TF\x10\x02\x12\x12\n\x0eOptionContract\x10\x03\x12\x12\n\x0e\x46utureContract\x10\x04\x12\t\n\x05\x46orex\x10\x05\x12\t\n\x05Index\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instrument_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTRUMENTKIND._serialized_start=391
  _INSTRUMENTKIND._serialized_end=502
  _EXCHANGE._serialized_start=50
  _EXCHANGE._serialized_end=175
  _INSTRUMENT._serialized_start=178
  _INSTRUMENT._serialized_end=327
  _INSTRUMENTLIST._serialized_start=329
  _INSTRUMENTLIST._serialized_end=389
# @@protoc_insertion_point(module_scope)
