# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: omen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util_pb2 as util__pb2
import tick_pb2 as tick__pb2
import order_pb2 as order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nomen.proto\x12\nworld.omen\x1a\nutil.proto\x1a\ntick.proto\x1a\x0border.proto\"\x0b\n\tOmenSmoke\"\x9b\x02\n\x04Omen\x12\t\n\x01t\x18\x01 \x01(\x03\x12\x31\n\tdirection\x18\x02 \x01(\x0e\x32\x19.world.omen.OmenDirectionH\x00\x88\x01\x01\x12*\n\x05order\x18\x03 \x01(\x0b\x32\x16.world.order.OmenOrderH\x01\x88\x01\x01\x12#\n\x04tick\x18\x04 \x01(\x0b\x32\x10.world.tick.TickH\x02\x88\x01\x01\x12\x0f\n\x07numbers\x18\x05 \x03(\x01\x12\x0c\n\x04text\x18\x06 \x03(\t\x12\x14\n\x07special\x18\x07 \x01(\x0cH\x03\x88\x01\x01\x12\"\n\x04kind\x18\x08 \x01(\x0e\x32\x14.world.omen.OmenKindB\x0c\n\n_directionB\x08\n\x06_orderB\x07\n\x05_tickB\n\n\x08_special\"C\n\x0eOmenSeriesItem\x12\x11\n\tseries_id\x18\x01 \x01(\t\x12\x1e\n\x04omen\x18\x02 \x01(\x0b\x32\x10.world.omen.Omen\"M\n\x16ScenarioOmenSeriesItem\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\x12\x1e\n\x04omen\x18\x02 \x01(\x0b\x32\x10.world.omen.Omen\"\x86\x01\n\x0eOmenSeriesInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x03(\t\x12\x19\n\x11instrument_ticker\x18\x04 \x03(\t\x12\x17\n\x0fscenario_ticker\x18\x05 \x03(\t\x12$\n\x05\x63ycle\x18\x06 \x01(\x0b\x32\x15.world.util.Frequency\">\n\x12OmenSeriesInfoList\x12(\n\x04list\x18\x01 \x03(\x0b\x32\x1a.world.omen.OmenSeriesInfo\"m\n\nOmenFilter\x12\x12\n\x05since\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x11\n\x04\x62son\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12%\n\x06ranges\x18\x03 \x03(\x0b\x32\x15.world.util.TimeRangeB\x08\n\x06_sinceB\x07\n\x05_bson*!\n\rOmenDirection\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01*h\n\x08OmenKind\x12\r\n\tDirection\x10\x00\x12\x08\n\x04Tick\x10\x01\x12\t\n\x05Order\x10\x02\x12\x0b\n\x07Numbers\x10\x03\x12\x08\n\x04Text\x10\x04\x12\t\n\x05Mixed\x10\x05\x12\x0b\n\x07Special\x10\x06\x12\t\n\x05Smoke\x10\x07\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omen_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OMENDIRECTION._serialized_start=822
  _OMENDIRECTION._serialized_end=855
  _OMENKIND._serialized_start=857
  _OMENKIND._serialized_end=961
  _OMENSMOKE._serialized_start=63
  _OMENSMOKE._serialized_end=74
  _OMEN._serialized_start=77
  _OMEN._serialized_end=360
  _OMENSERIESITEM._serialized_start=362
  _OMENSERIESITEM._serialized_end=429
  _SCENARIOOMENSERIESITEM._serialized_start=431
  _SCENARIOOMENSERIESITEM._serialized_end=508
  _OMENSERIESINFO._serialized_start=511
  _OMENSERIESINFO._serialized_end=645
  _OMENSERIESINFOLIST._serialized_start=647
  _OMENSERIESINFOLIST._serialized_end=709
  _OMENFILTER._serialized_start=711
  _OMENFILTER._serialized_end=820
# @@protoc_insertion_point(module_scope)
