# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x0bworld.order\"\xd1\x04\n\tOmenOrder\x12\x12\n\ninstrument\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12,\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x1c.world.order.OmenOrderAction\x12\r\n\x05short\x18\x04 \x01(\x08\x12\x12\n\x05price\x18\x05 \x01(\x01H\x00\x88\x01\x01\x12\x11\n\x04stop\x18\x06 \x01(\x01H\x01\x88\x01\x01\x12\x12\n\x05limit\x18\x07 \x01(\x01H\x02\x88\x01\x01\x12(\n\x04kind\x18\x08 \x01(\x0e\x32\x1a.world.order.OmenOrderKind\x12\x1a\n\x12\x61ssociated_numbers\x18\t \x03(\x01\x12\x18\n\x0bpercentages\x18\n \x01(\x08H\x03\x88\x01\x01\x12\x15\n\x08order_id\x18\x0b \x01(\tH\x04\x88\x01\x01\x12\x19\n\x11\x61ssociated_orders\x18\x0c \x03(\t\x12\x14\n\x0crunning_from\x18\r \x03(\x03\x12\x1a\n\rrunning_until\x18\x0e \x01(\x03H\x05\x88\x01\x01\x12\x12\n\norder_time\x18\x0f \x03(\x03\x12\x31\n\x06status\x18\x10 \x01(\x0e\x32\x1c.world.order.OmenOrderStatusH\x06\x88\x01\x01\x12\x15\n\x08\x65xchange\x18\x11 \x01(\tH\x07\x88\x01\x01\x12\x14\n\x07special\x18\x12 \x01(\x0cH\x08\x88\x01\x01\x42\x08\n\x06_priceB\x07\n\x05_stopB\x08\n\x06_limitB\x0e\n\x0c_percentagesB\x0b\n\t_order_idB\x10\n\x0e_running_untilB\t\n\x07_statusB\x0b\n\t_exchangeB\n\n\x08_special*e\n\rOmenOrderKind\x12\t\n\x05Limit\x10\x00\x12\x08\n\x04Stop\x10\x01\x12\r\n\tLimitStop\x10\x02\x12\x0c\n\x08Trailing\x10\x03\x12\n\n\x06Market\x10\x04\x12\t\n\x05Mixed\x10\x05\x12\x0b\n\x07Special\x10\x06*:\n\x0fOmenOrderStatus\x12\x0b\n\x07PENDING\x10\x00\x12\x0c\n\x08\x45XECUTED\x10\x01\x12\x0c\n\x08\x43\x41NCELED\x10\x02*$\n\x0fOmenOrderAction\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OMENORDERKIND._serialized_start=624
  _OMENORDERKIND._serialized_end=725
  _OMENORDERSTATUS._serialized_start=727
  _OMENORDERSTATUS._serialized_end=785
  _OMENORDERACTION._serialized_start=787
  _OMENORDERACTION._serialized_end=823
  _OMENORDER._serialized_start=29
  _OMENORDER._serialized_end=622
# @@protoc_insertion_point(module_scope)
