# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tick_pb2 as tick__pb2
import omen_pb2 as omen__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escenario.proto\x12\x0eworld.scenario\x1a\ntick.proto\x1a\nomen.proto\"O\n\rScenarioState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x03(\t\x12\x13\n\x0bscenario_id\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\x0c\"@\n\x11ScenarioStateList\x12+\n\x04list\x18\x01 \x03(\x0b\x32\x1d.world.scenario.ScenarioState\"M\n\x12ScenarioDependency\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\x12\x15\n\x08state_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_state_id\"J\n\x16ScenarioDependencyList\x12\x30\n\x04list\x18\x01 \x03(\x0b\x32\".world.scenario.ScenarioDependency\"l\n\x14ScenarioDependencies\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x03(\t\x12\x38\n\x0c\x64\x65pendencies\x18\x03 \x03(\x0b\x32\".world.scenario.ScenarioDependency\"N\n\x18ScenarioDependenciesList\x12\x32\n\x04list\x18\x01 \x03(\x0b\x32$.world.scenario.ScenarioDependencies\"i\n\x08Scenario\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x03(\t\x12\x0e\n\x06oracle\x18\x03 \x01(\t\x12\x1a\n\x12scenario_series_id\x18\x04 \x01(\t\x12\x15\n\rdefault_state\x18\x05 \x01(\t\"6\n\x0cScenarioList\x12&\n\x04list\x18\x01 \x03(\x0b\x32\x18.world.scenario.Scenariob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scenario_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENARIOSTATE._serialized_start=58
  _SCENARIOSTATE._serialized_end=137
  _SCENARIOSTATELIST._serialized_start=139
  _SCENARIOSTATELIST._serialized_end=203
  _SCENARIODEPENDENCY._serialized_start=205
  _SCENARIODEPENDENCY._serialized_end=282
  _SCENARIODEPENDENCYLIST._serialized_start=284
  _SCENARIODEPENDENCYLIST._serialized_end=358
  _SCENARIODEPENDENCIES._serialized_start=360
  _SCENARIODEPENDENCIES._serialized_end=468
  _SCENARIODEPENDENCIESLIST._serialized_start=470
  _SCENARIODEPENDENCIESLIST._serialized_end=548
  _SCENARIO._serialized_start=550
  _SCENARIO._serialized_end=655
  _SCENARIOLIST._serialized_start=657
  _SCENARIOLIST._serialized_end=711
# @@protoc_insertion_point(module_scope)
